export { default as AccountPage } from "./Accountpage";
export { default as RegisterPage } from "./RegisterPage";
export { default as HomePage } from "./Home";
export { default as LikedVideosPage } from "./LikedVideos";
export { default as PlaylistsPage } from "./Playlists";
export { default as PlaylistVideosPage } from "./PlaylistVideosPage";
export { default as VideoPage } from "./VideoPage";
export { default as WatchLaterPage } from "./WatchLaterPage";
export { default as SavedVideosPage } from "./SavedVideosPage";
