export const videoData = [
	{
		id: "1",
		videoId: "M5MD5i6VpYQ",
		name: "Cricket rules for Beginners",
		imageUrl: "https://img.youtube.com/vi/M5MD5i6VpYQ/hqdefault.jpg",
		description:
			"A beginner cricketer will most likely just want to give the ball a thump but if your youngster is ready for some simple coaching tips, this video covers the batting basics.",
		thumbnail:
			"https://i.ytimg.com/an_webp/VwII4y5vpyU/mqdefault_6s.webp?du=3000&sqp=CIiSzIMG&rs=AOn4CLDYM278Q7Uaf4zrgG3GnVJ4v1O6jA",
		liked: false,
		watchLater: false,
		playLists: [],
		views: "4.6M",
		likes: "18k",
		dislikes: "767",
		watchLength: "12:07",
		publishedDate: "August 7,2019",
	},
	{
		id: "2",
		videoId: "ro38zYAXdcs",
		name: "How to focus on Ball",
		imageUrl: "https://img.youtube.com/vi/ro38zYAXdcs/hqdefault.jpg",
		description:
			"A beginner cricketer will most likely just want to give the ball a thump but if your youngster is ready for some simple coaching tips, this video covers the batting basics.",
		thumbnail:
			"https://i.ytimg.com/an_webp/ro38zYAXdcs/mqdefault_6s.webp?du=3000&sqp=CLD4wYMG&rs=AOn4CLBr26lip4XEvbS_k9Tw94jmCHNxSQ",
		liked: false,
		watchLater: false,
		playLists: [],
		views: "4.6M",
		likes: "18k",
		dislikes: "767",
		watchLength: "12:07",
		publishedDate: "August 7,2019",
	},
	{
		id: "3",
		videoId: "8oOj2x4_OMs",
		name: "Batting for Beginners",
		imageUrl: "https://img.youtube.com/vi/8oOj2x4_OMs/hqdefault.jpg",
		description:
			"A beginner cricketer will most likely just want to give the ball a thump but if your youngster is ready for some simple coaching tips, this video covers the batting basics.",
		thumbnail:
			"https://i.ytimg.com/an_webp/8oOj2x4_OMs/mqdefault_6s.webp?du=3000&sqp=CK3kwYMG&rs=AOn4CLDYBM2GZeKi9q6lbG4X37MPecnNrA",
		liked: false,
		watchLater: false,
		playLists: [],
		views: "1.5M",
		likes: "18k",
		dislikes: "767",
		watchLength: "12:07",
		publishedDate: "August 7,2019",
	},
	// {
	// 	id: "",
	// 	name: "",
	// 	thumbnail: "",
	// 	liked: false,
	// 	watchLater: false,
	// 	playLists: [],
	// },
	// {
	// 	id: "",
	// 	name: "",
	// 	thumbnail: "",
	// 	liked: false,
	// 	watchLater: false,
	// 	playLists: [],
	// },
];
